EMBED_COLOR = 0xdba632

PERMISSIONS_PT = {
    'create_instant_invite': 'Criar convite instantâneo',
    'kick_members': 'Expulsar membros',
    'ban_members': 'Banir membros',
    'administrator': 'Administrador',
    'manage_channels': 'Gerenciar canais',
    'manage_guild': 'Gerenciar servidor',
    'add_reactions': 'Adicionar reações',
    'view_audit_log': 'Ver registro de auditoria',
    'priority_speaker': 'Voz prioritária',
    'stream': 'Stream',
    'read_messages': 'Ler mensagens',
    'send_messages': 'Enviar mensagens',
    'send_tts_messages': 'Enviar mensagens de texto-para-voz',
    'manage_messages': 'Gerenciar mensagens',
    'embed_links': 'Inserir links',
    'attach_files': 'Anexar arquivos',
    'read_message_history': 'Ver histórico de mensagens',
    'mention_everyone': 'Mencionar @everyone, @here e todos os cargos',
    'external_emojis': 'Usar emojis externos',
    'view_guild_insights': 'Ver insignias do servidor',
    'connect': 'Conectar',
    'speak': 'Falar',
    'mute_members': 'Silenciar membros',
    'deafen_members': 'Ensurdecer membros',
    'move_members': 'Mover membros',
    'use_voice_activation': 'Usar ativação por voz',
    'change_nickname': 'Alterar apelido',
    'manage_nicknames': 'Gerenciar apelidos',
    'manage_roles': 'Gerenciar cargos',
    'manage_webhooks': 'Gerenciar webhooks',
    'manage_emojis': 'Gerenciar emojis',
    'use_application_commands': 'Usar comandos de aplicativos',
    'request_to_speak' : 'Pedir para falar',
    'manage_events' : 'Gerenciar eventos',
    'manage_threads' : 'Gerenciar tópicos',
    'create_public_threads' : 'Criar tópicos públicos',
    'create_private_threads' : 'Criar tópicos privados',
    'external_stickers' : 'Usar figurinhas externas',
    'send_messages_in_threads' : 'Enviar mensagens nos tópicos',
    'use_embedded_activities' : 'Usar atividades',
    'moderate_members' : 'Moderar membros',
}

badges = {
    'verified_bot': '<:VerifiedBOT:1109864507737636924>',
    'active_developer': '<:BadgeActiveDeveloper:1109878079234506752>',
    'verified_bot_developer': '<:BadgeVerifiedBotDeveloper:1109880950768279704>',

    'hypesquad': '<:BadgeHypeSquad:1109881142737371219>',
    'hypesquad_balance': '<:BadgeBalance:1109880408121823333>',
    'hypesquad_bravery': '<:BadgeBravery:1109880728436609135>',
    'hypesquad_brilliance': '<:BadgeBrilliance:1109881530551107624>',

    'partner': '<:BadgePartner:1109880481249501274>',
    'bug_hunter': '<:BadgeBugHunter:1109860228180226128>',
    'bug_hunter_level_2': '<:BadgeBugHunterLvl2:1109860251085324338>',
    'early_supporter': '<:BadgeEarlySupporter:1109880637046919228>',
    'staff': '<:BadgeStaff:1109860438516179074>',
    'discord_certified_moderator': '<:BadgeModeratorProgramsAlumni:1109860396195659868>'
}
